// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_AJLtT_x46uPgChIGRD_Dj8neP_lNLjQ',
    appId: '1:734076911463:web:54a4ed2681108ad823b9c2',
    messagingSenderId: '734076911463',
    projectId: 'mood-diary-app-b5f5b',
    authDomain: 'mood-diary-app-b5f5b.firebaseapp.com',
    storageBucket: 'mood-diary-app-b5f5b.firebasestorage.app',
    measurementId: 'G-37ZX2JKWTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMBjwIjMcEBILNqdcWp3bbfmTpAJ8jTRk',
    appId: '1:734076911463:android:94af49c01398b0cc23b9c2',
    messagingSenderId: '734076911463',
    projectId: 'mood-diary-app-b5f5b',
    storageBucket: 'mood-diary-app-b5f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIlOVVC7lfF4VKQmZi1sTehvxNnx-3Zn0',
    appId: '1:734076911463:ios:3e3c0836fda1b98223b9c2',
    messagingSenderId: '734076911463',
    projectId: 'mood-diary-app-b5f5b',
    storageBucket: 'mood-diary-app-b5f5b.firebasestorage.app',
    iosBundleId: 'com.example.moodDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIlOVVC7lfF4VKQmZi1sTehvxNnx-3Zn0',
    appId: '1:734076911463:ios:3e3c0836fda1b98223b9c2',
    messagingSenderId: '734076911463',
    projectId: 'mood-diary-app-b5f5b',
    storageBucket: 'mood-diary-app-b5f5b.firebasestorage.app',
    iosBundleId: 'com.example.moodDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_AJLtT_x46uPgChIGRD_Dj8neP_lNLjQ',
    appId: '1:734076911463:web:d85db165d11a374123b9c2',
    messagingSenderId: '734076911463',
    projectId: 'mood-diary-app-b5f5b',
    authDomain: 'mood-diary-app-b5f5b.firebaseapp.com',
    storageBucket: 'mood-diary-app-b5f5b.firebasestorage.app',
    measurementId: 'G-GLZ5Y1QY4F',
  );
}
